### ISSUE TITLE
相册

### ISSUE THREAD

**Issue by yly123223** [WatsonYao/nian_app#91]
在手机的相册软件里找不到nian的相册 但是在文件夹里有专门nian的相册 这样有影响吗 我也打开了图片插入方式 如果这样的话我把相册里的图放在nian的某个日记里 在原相册删掉图片 会对日记里的图有影响吗
![Screenshot_2024-10-02-00-26-31-87_164c5e772435b259a7d41e069b35641e](https://github.com/user-attachments/assets/5b6a2661-4a2a-4bda-915b-b7c080c17baf)
![Screenshot_2024-10-02-00-21-29-97_99c04817c0de5652397fc8b56c3b3817](https://github.com/user-attachments/assets/a05f2ef6-a126-447a-ad0d-a7d4bb06430d)
![Screenshot_2024-10-02-00-21-46-32_55bef12f624c2b805189a6aa783c400d](https://github.com/user-attachments/assets/cfa3433b-74c1-4605-8476-ff24e38426f0)

**Comment by WatsonYao** [comment]
问题最好发到讨论组里面，这里的先关闭了。你可以参考新手指南的帮助文档的详细说明。
